import Link from 'next/link';
import { BriefcaseBusiness, Search, Users } from 'lucide-react';
import { AppShell } from '../../components/app-shell';
import { money } from '../../lib/format';
import { getCurrentProfile } from '../../lib/current-profile';
import { createSupabaseServerClient } from '../../lib/supabase/server';

type Customer={id:string;customer_number:string;name:string;phone:string|null};
type Job={id:string;job_number:string;title:string;stage:string;grand_total_satang:number;customer:{name:string}|null};
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string}>}){const {q=''}=await searchParams;const term=q.trim();const profile=await getCurrentProfile();const supabase=await createSupabaseServerClient();let customers:Customer[]=[];let jobs:Job[]=[];if(term){const [{data:customerData},{data:jobData}]=await Promise.all([supabase.from('customers').select('id,customer_number,name,phone').or(`name.ilike.%${term}%,phone.ilike.%${term}%,customer_number.ilike.%${term}%`).limit(20),supabase.from('jobs').select('id,job_number,title,stage,grand_total_satang,customer:customers(name)').or(`job_number.ilike.%${term}%,title.ilike.%${term}%`).limit(20)]);customers=(customerData??[]) as Customer[];jobs=(jobData??[]) as unknown as Job[];}return <AppShell profile={profile} active="/search"><div className="section-heading"><div><p>ค้นหาทั้งระบบ</p><h1>{term?`ผลการค้นหา “${term}”`:'ค้นหาข้อมูล'}</h1><span>เลขที่งาน ชื่องาน ชื่อลูกค้า และเบอร์โทร</span></div></div>{!term?<div className="empty-state standalone"><Search/><h3>พิมพ์คำค้นที่ช่องด้านบน</h3><p>ระบบจะค้นหาลูกค้าและ Job พร้อมกัน</p></div>:<div className="search-results"><section className="panel"><div className="panel-header"><div><h2><Users size={17}/>ลูกค้า</h2><p>{customers.length} รายการ</p></div></div>{customers.length?customers.map((customer)=><Link className="result-row" href={`/customers?q=${encodeURIComponent(customer.customer_number)}`} key={customer.id}><span><strong>{customer.name}</strong><small>{customer.customer_number} · {customer.phone??'ไม่มีเบอร์โทร'}</small></span></Link>):<div className="mini-empty">ไม่พบลูกค้า</div>}</section><section className="panel"><div className="panel-header"><div><h2><BriefcaseBusiness size={17}/>งาน</h2><p>{jobs.length} รายการ</p></div></div>{jobs.length?jobs.map((job)=><Link className="result-row" href={`/jobs/${job.id}`} key={job.id}><span><strong>{job.job_number} · {job.title}</strong><small>{job.customer?.name??'-'} · {job.stage}</small></span><b>{money(job.grand_total_satang)}</b></Link>):<div className="mini-empty">ไม่พบงาน</div>}</section></div>}</AppShell>;}

