import Link from 'next/link';
import { Search, UserPlus, Users } from 'lucide-react';
import { AppShell } from '../../components/app-shell';
import { getCurrentProfile } from '../../lib/current-profile';
import { createSupabaseServerClient } from '../../lib/supabase/server';

type Customer = { id: string; customer_number: string; name: string; customer_type: string; phone: string | null; line_name: string | null; created_at: string; lead_source: { name: string } | null };
export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string; created?: string }> }) {
  const params = await searchParams; const profile = await getCurrentProfile(); const supabase = await createSupabaseServerClient();
  let query = supabase.from('customers').select('id,customer_number,name,customer_type,phone,line_name,created_at,lead_source:lead_sources(name)').order('created_at', { ascending: false });
  if (params.q?.trim()) query = query.or(`name.ilike.%${params.q.trim()}%,phone.ilike.%${params.q.trim()}%,customer_number.ilike.%${params.q.trim()}%`);
  const { data, error } = await query; const customers = (data ?? []) as unknown as Customer[];
  return <AppShell profile={profile} active="/customers" createHref="/customers/new"><div className="section-heading"><div><p>งานขาย</p><h1>ลูกค้า</h1><span>ค้นหาและจัดการข้อมูลลูกค้าทั้งหมด</span></div><Link className="primary-button" href="/customers/new"><UserPlus size={17} />เพิ่มลูกค้า</Link></div>{params.created ? <div className="success-banner">บันทึกลูกค้าเรียบร้อยแล้ว</div> : null}<section className="panel list-panel"><div className="list-toolbar"><form><Search size={17} /><input name="q" defaultValue={params.q} placeholder="ค้นหาชื่อ เบอร์โทร หรือรหัสลูกค้า" /><button>ค้นหา</button></form><span>{customers.length} รายการ</span></div>{error ? <div className="error-state">โหลดข้อมูลไม่สำเร็จ: {error.message}</div> : customers.length ? <div className="table-wrap"><table><thead><tr><th>รหัส</th><th>ลูกค้า</th><th>เบอร์โทร</th><th>LINE</th><th>ช่องทาง</th><th>วันที่เพิ่ม</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td><strong>{customer.customer_number}</strong></td><td><span className="customer-cell"><i>{customer.name.slice(0,1)}</i><span><strong>{customer.name}</strong><small>{customer.customer_type === 'BUSINESS' ? 'บริษัท / ร้านค้า' : 'บุคคล'}</small></span></span></td><td>{customer.phone ?? '-'}</td><td>{customer.line_name ?? '-'}</td><td>{customer.lead_source?.name ?? '-'}</td><td>{new Intl.DateTimeFormat('th-TH', { dateStyle: 'medium', timeZone: 'Asia/Bangkok' }).format(new Date(customer.created_at))}</td></tr>)}</tbody></table></div> : <div className="empty-state"><Users /><h3>ยังไม่มีลูกค้า</h3><p>เริ่มจากเพิ่มลูกค้ารายแรก</p><Link className="primary-button" href="/customers/new">เพิ่มลูกค้า</Link></div>}</section></AppShell>;
}
