'use client';

import { FormEvent, useState } from 'react';
import { createSupabaseBrowserClient } from '../../lib/supabase/client';

export function ForgotPasswordForm(){const[message,setMessage]=useState('');const[error,setError]=useState('');const[pending,setPending]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setMessage('');setPending(true);const email=String(new FormData(event.currentTarget).get('email')??'').trim();const supabase=createSupabaseBrowserClient();const{error:requestError}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(requestError)setError(requestError.message);else setMessage('ส่งลิงก์ตั้งรหัสผ่านใหม่แล้ว กรุณาตรวจอีเมล');setPending(false);}return <form onSubmit={submit} className="login-form"><label><span>อีเมล</span><div><input name="email" type="email" required/></div></label>{error?<p className="form-error">{error}</p>:null}{message?<p className="form-success">{message}</p>:null}<button disabled={pending}>{pending?'กำลังส่ง…':'ส่งลิงก์ตั้งรหัสผ่านใหม่'}</button></form>;}

export function ResetPasswordForm(){const[message,setMessage]=useState('');const[error,setError]=useState('');const[pending,setPending]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setMessage('');setPending(true);const password=String(new FormData(event.currentTarget).get('password')??'');const supabase=createSupabaseBrowserClient();const{error:updateError}=await supabase.auth.updateUser({password});if(updateError)setError(updateError.message);else setMessage('ตั้งรหัสผ่านใหม่แล้ว กลับไปเข้าสู่ระบบได้ทันที');setPending(false);}return <form onSubmit={submit} className="login-form"><label><span>รหัสผ่านใหม่</span><div><input name="password" type="password" minLength={8} required/></div></label>{error?<p className="form-error">{error}</p>:null}{message?<p className="form-success">{message}</p>:null}<button disabled={pending}>{pending?'กำลังบันทึก…':'ตั้งรหัสผ่านใหม่'}</button></form>;}

