'use client';
import { useState } from 'react';
import { CalendarDays, CheckCircle2, Grid2X2, ImageOff, List, Wrench } from 'lucide-react';
import { confirmTechnicianAssemblyAction } from '../jobs/actions';
type Brief = { quantity: number; dimensions: string | null; material: string | null; requirements: string | null } | null;
type Job = { id: string; job_number: string; title: string; deadline: string | null; customer: { name: string } | null; brief: Brief };

function details(brief: Brief) {
  if (!brief?.requirements) return { materials: brief?.material ? [brief.material] : [], finishing: [] as string[], shapes: [] as string[] };
  try { const spec = JSON.parse(brief.requirements); return { materials: spec.materials || [], finishing: spec.finishing || [], shapes: spec.shapes || [] }; } catch { return { materials: brief.material ? [brief.material] : [], finishing: [], shapes: [] }; }
}
export function TechnicianJobsView({ jobs, thumbnails }: { jobs: Job[]; thumbnails: Record<string, string> }) { const [view, setView] = useState<'cards' | 'list'>('cards'); return <><div className="jobs-view-toggle" role="group" aria-label="รูปแบบการแสดงผล"><button type="button" className={view === 'cards' ? 'active' : ''} onClick={() => setView('cards')}><Grid2X2 size={15} /> การ์ด</button><button type="button" className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={15} /> รายการ</button></div>{view === 'cards' ? <div className="customer-job-cards">{jobs.map((job) => { const d = details(job.brief); return <article className="customer-job-card" key={job.id}><div className="customer-job-card-image">{thumbnails[job.id] ? <img src={thumbnails[job.id]} alt={`ภาพตัวอย่าง ${job.title}`} /> : <><ImageOff size={26} /><span>ยังไม่มีภาพตัวอย่าง</span></>}<span className="badge amber customer-job-card-stage">รอผลิต</span></div><div className="customer-job-card-body"><div className="customer-job-card-top"><strong className="technician-job-number">#{job.job_number}</strong><Wrench size={15} /></div><h3 className="technician-job-title">{job.title}</h3><div className="technician-job-quantity">จำนวน <strong>{job.brief?.quantity ?? 1} ชิ้น</strong></div><div className="technician-job-specs"><span>ขนาด: {job.brief?.dimensions || '-'}</span>{[...d.materials, ...d.finishing, ...d.shapes].map((item: string) => <span key={item}>{item}</span>)}</div><div className="customer-job-card-meta"><span>{job.customer?.name ?? 'ไม่ระบุลูกค้า'}</span><span><CalendarDays size={14} /> {job.deadline ? new Intl.DateTimeFormat('th-TH', { dateStyle: 'medium', timeZone: 'Asia/Bangkok' }).format(new Date(job.deadline)) : 'ไม่ระบุกำหนดส่ง'}</span></div><ConfirmButton jobId={job.id} /></div></article>; })}</div> : <div className="table-wrap"><table><thead><tr><th>เลขที่งาน</th><th>ชื่องาน</th><th>รายละเอียด</th><th>การดำเนินการ</th></tr></thead><tbody>{jobs.map((job) => { const d = details(job.brief); return <tr key={job.id}><td><strong className="technician-job-number">{job.job_number}</strong></td><td><strong className="technician-job-title">{job.title}</strong></td><td>{job.brief?.quantity ?? 1} ชิ้น · {job.brief?.dimensions || '-'} · {[...d.materials, ...d.finishing, ...d.shapes].join(', ') || '-'}</td><td><ConfirmButton jobId={job.id} /></td></tr>; })}</tbody></table></div>}</>; }
function ConfirmButton({ jobId }: { jobId: string }) { return <form action={confirmTechnicianAssemblyAction}><input type="hidden" name="jobId" value={jobId} /><button className="primary-button" type="submit"><CheckCircle2 size={16} /> ยืนยันประกอบงาน</button></form>; }
