'use client';

import { useActionState } from 'react';
import { type SettingsState, updateSettingsAction } from './actions';

type Organization={name:string;phone:string|null;email:string|null;tax_id:string|null;address:string|null;vat_registered:boolean;allow_withholding_tax:boolean;quotation_note:string|null;promptpay_name:string|null;promptpay_number:string|null;bank_name:string|null;bank_account_name:string|null;bank_account_number:string|null};

export function OrganizationSettingsForm({organization,ownerName}:{organization:Organization;ownerName:string}){
  const [state,action,pending]=useActionState(updateSettingsAction,{} as SettingsState);
  return <form action={action} className="data-form"><div className="form-grid"><label><span>ชื่อองค์กร</span><input name="organizationName" defaultValue={organization.name} required/></label><label><span>ชื่อ Owner</span><input name="ownerName" defaultValue={ownerName} required/></label><label><span>เบอร์โทรองค์กร</span><input name="phone" defaultValue={organization.phone??''}/></label><label><span>อีเมล</span><input name="email" type="email" defaultValue={organization.email??''}/></label><label><span>เลขประจำตัวผู้เสียภาษี</span><input name="taxId" defaultValue={organization.tax_id??''}/></label><label className="span-2"><span>ที่อยู่</span><textarea name="address" rows={3} defaultValue={organization.address??''}/></label><label className="checkbox-field"><input name="vatRegistered" type="checkbox" defaultChecked={organization.vat_registered}/><span>จดทะเบียน VAT 7%</span></label><label className="checkbox-field"><input name="allowWithholding" type="checkbox" defaultChecked={organization.allow_withholding_tax}/><span>รองรับหัก ณ ที่จ่าย</span></label><label className="span-2"><span>หมายเหตุท้ายใบเสนอราคา</span><textarea name="quotationNote" rows={3} defaultValue={organization.quotation_note??''}/></label><label><span>ชื่อ PromptPay</span><input name="promptpayName" defaultValue={organization.promptpay_name??''}/></label><label><span>หมายเลข PromptPay</span><input name="promptpayNumber" defaultValue={organization.promptpay_number??''}/></label><label><span>ธนาคาร</span><input name="bankName" defaultValue={organization.bank_name??''}/></label><label><span>ชื่อบัญชี</span><input name="bankAccountName" defaultValue={organization.bank_account_name??''}/></label><label className="span-2"><span>เลขบัญชี</span><input name="bankAccountNumber" defaultValue={organization.bank_account_number??''}/></label></div>{state.error?<p className="form-error">{state.error}</p>:null}{state.success?<p className="form-success">{state.success}</p>:null}<div className="form-actions"><button className="primary-button" disabled={pending}>{pending?'กำลังบันทึก…':'บันทึกการตั้งค่า'}</button></div></form>;
}
