import { notFound } from 'next/navigation';
import Link from 'next/link';
import { BriefcaseBusiness, CheckCircle2, FileText } from 'lucide-react';
import { AppShell } from '../../../components/app-shell';
import { money, thaiDate } from '../../../lib/format';
import { getCurrentProfile } from '../../../lib/current-profile';
import { createSupabaseServerClient } from '../../../lib/supabase/server';
import { createJobFromQuotationAction, updateQuotationStatusAction } from '../actions';

type Item={id:string;description:string;quantity:number;unit:string;unit_price_satang:number;line_total_satang:number;sort_order:number};
type Quotation={id:string;quotation_number:string;title:string;status:string;valid_until:string|null;subtotal_satang:number;discount_satang:number;vat_rate:number;vat_satang:number;withholding_tax_rate:number;withholding_tax_satang:number;grand_total_satang:number;note:string|null;job_id:string|null;customer:{name:string;phone:string|null;email:string|null}|null;items:Item[]};
const statusLabel:Record<string,string>={DRAFT:'ฉบับร่าง',SENT:'ส่งให้ลูกค้าแล้ว',ACCEPTED:'ลูกค้าอนุมัติ',REJECTED:'ลูกค้าไม่อนุมัติ',CANCELLED:'ยกเลิก'};

export default async function QuotationDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{created?:string;error?:string}>}){
  const {id}=await params; const query=await searchParams; const profile=await getCurrentProfile(); const supabase=await createSupabaseServerClient();
  const {data}=await supabase.from('quotations').select('id,quotation_number,title,status,valid_until,subtotal_satang,discount_satang,vat_rate,vat_satang,withholding_tax_rate,withholding_tax_satang,grand_total_satang,note,job_id,customer:customers(name,phone,email),items:quotation_items(id,description,quantity,unit,unit_price_satang,line_total_satang,sort_order)').eq('id',id).single();
  if(!data)notFound(); const quotation=data as unknown as Quotation;
  return <AppShell profile={profile} active="/quotations">{query.created?<div className="success-banner">สร้างใบเสนอราคาเรียบร้อยแล้ว</div>:null}{query.error?<div className="form-error">ยังสร้าง Job ไม่ได้ กรุณาเปลี่ยนสถานะเป็นส่งแล้วหรืออนุมัติก่อน</div>:null}<div className="job-header"><div><p>{quotation.quotation_number}</p><h1>{quotation.title}</h1><span>{quotation.customer?.name} · {statusLabel[quotation.status]}</span></div><div className="header-actions">{quotation.job_id?<Link className="primary-button" href={`/jobs/${quotation.job_id}`}><BriefcaseBusiness size={16}/>เปิด Job</Link>:quotation.status==='SENT'||quotation.status==='ACCEPTED'?<form action={createJobFromQuotationAction}><input type="hidden" name="quotationId" value={quotation.id}/><button className="primary-button"><BriefcaseBusiness size={16}/>สร้าง Job</button></form>:null}</div></div><div className="detail-grid"><div className="detail-main"><section className="panel detail-card"><div className="panel-header"><div><h2><FileText size={17}/>รายการเสนอราคา</h2><p>{quotation.valid_until?`ใช้ได้ถึง ${thaiDate(quotation.valid_until)}`:'ไม่ระบุวันหมดอายุ'}</p></div></div><div className="table-wrap"><table><thead><tr><th>รายการ</th><th>จำนวน</th><th>ราคา/หน่วย</th><th>รวม</th></tr></thead><tbody>{quotation.items.sort((a,b)=>a.sort_order-b.sort_order).map((item)=><tr key={item.id}><td><strong>{item.description}</strong></td><td>{item.quantity} {item.unit}</td><td>{money(item.unit_price_satang)}</td><td>{money(item.line_total_satang)}</td></tr>)}</tbody></table></div></section><section className="panel form-panel"><h2>เปลี่ยนสถานะ</h2><div className="status-actions">{['DRAFT','SENT','ACCEPTED','REJECTED','CANCELLED'].map((status)=><form action={updateQuotationStatusAction} key={status}><input type="hidden" name="quotationId" value={quotation.id}/><input type="hidden" name="status" value={status}/><button className={quotation.status===status?'primary-button':'secondary-button'} disabled={quotation.status===status}>{statusLabel[status]}</button></form>)}</div></section></div><aside className="detail-side"><section className="panel finance-card"><div className="panel-header"><div><h2><CheckCircle2 size={17}/>สรุปยอด</h2></div></div><div className="finance-numbers"><span>รวมรายการ<strong>{money(quotation.subtotal_satang)}</strong></span><span>ส่วนลด<strong>-{money(quotation.discount_satang)}</strong></span><span>VAT {quotation.vat_rate}%<strong>{money(quotation.vat_satang)}</strong></span><span>หัก ณ ที่จ่าย {quotation.withholding_tax_rate}%<strong>-{money(quotation.withholding_tax_satang)}</strong></span><span>ยอดสุทธิ<strong className="paid">{money(quotation.grand_total_satang)}</strong></span></div></section><section className="panel info-card"><p>โทร: {quotation.customer?.phone??'-'}</p><p>อีเมล: {quotation.customer?.email??'-'}</p><p>{quotation.note??'ไม่มีหมายเหตุ'}</p></section></aside></div></AppShell>;
}
