import { notFound } from 'next/navigation';
import { Banknote, CalendarDays, CheckCircle2, CircleDot, PackageCheck, UserRound } from 'lucide-react';
import { AppShell } from '../../../components/app-shell';
import { getCurrentProfile } from '../../../lib/current-profile';
import { createSupabaseServerClient } from '../../../lib/supabase/server';
import { recordPaymentAction, updateJobStageAction } from '../actions';

type JobDetail = { id:string; job_number:string; title:string; stage:string; status:string; priority:string; deadline:string|null; grand_total_satang:number; paid_amount_satang:number; created_at:string; assigned_graphic_id:string|null; customer:{name:string;phone:string|null;line_name:string|null}|null; brief:{requirements:string;dimensions:string|null;material:string|null;quantity:number}|null };
type Payment = { id:string; amount_satang:number; method:string; paid_at:string; reference:string|null };
type Activity = { id:string; action:string; created_at:string; user:{full_name:string}|null };
const stages = ['ADMIN','DESIGN','PRODUCTION','DELIVERY','COMPLETE'] as const;
const labels: Record<string,string> = { ADMIN:'รับงาน',DESIGN:'ออกแบบ',PRODUCTION:'ผลิต',DELIVERY:'ส่งมอบ',COMPLETE:'เสร็จสิ้น' };
const nextStage: Record<string,string|undefined> = { ADMIN:'DESIGN',DESIGN:'PRODUCTION',PRODUCTION:'DELIVERY',DELIVERY:'COMPLETE' };
const actionLabels: Record<string,string> = { JOB_CREATED:'สร้าง Job',STAGE_CHANGED_DESIGN:'ส่งเข้าฝ่ายออกแบบ',STAGE_CHANGED_PRODUCTION:'อนุมัติและส่งผลิต',STAGE_CHANGED_DELIVERY:'ผลิตเสร็จและรอส่งมอบ',STAGE_CHANGED_COMPLETE:'ปิด Job' };
const money = (satang:number)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(satang/100);

export default async function JobDetailPage({ params, searchParams }: { params:Promise<{id:string}>; searchParams:Promise<{created?:string}> }) {
  const { id } = await params; const query = await searchParams; const profile = await getCurrentProfile(); const supabase = await createSupabaseServerClient();
  const [{data:jobData},{data:paymentsData},{data:activitiesData}] = await Promise.all([
    supabase.from('jobs').select('id,job_number,title,stage,status,priority,deadline,grand_total_satang,paid_amount_satang,created_at,assigned_graphic_id,customer:customers(name,phone,line_name),brief:briefs(requirements,dimensions,material,quantity)').eq('id',id).single(),
    supabase.from('payments').select('id,amount_satang,method,paid_at,reference').eq('job_id',id).order('paid_at',{ascending:false}),
    supabase.from('activity_logs').select('id,action,created_at,user:profiles(full_name)').eq('entity_id',id).order('created_at',{ascending:false}),
  ]);
  if (!jobData) notFound(); const job = jobData as unknown as JobDetail; const payments=(paymentsData??[]) as Payment[]; const activities=(activitiesData??[]) as unknown as Activity[]; const remaining=job.grand_total_satang-job.paid_amount_satang; const currentIndex=stages.indexOf(job.stage as typeof stages[number]);
  return <AppShell profile={profile} active="/jobs">{query.created?<div className="success-banner">เปิด Job และสร้างเลขที่งานเรียบร้อยแล้ว</div>:null}<div className="job-header"><div><p>{job.job_number}</p><h1>{job.title}</h1><span>{job.customer?.name??'-'} · {job.priority}</span></div>{nextStage[job.stage]?<form action={updateJobStageAction}><input type="hidden" name="jobId" value={job.id}/><input type="hidden" name="stage" value={nextStage[job.stage]}/><button className="primary-button"><PackageCheck size={17}/>{job.stage==='ADMIN'?'ส่งออกแบบ':job.stage==='DESIGN'?'อนุมัติและส่งผลิต':job.stage==='PRODUCTION'?'ผลิตเสร็จ':job.stage==='DELIVERY'?'ปิด Job':'อัปเดต'}</button></form>:<span className="complete-badge"><CheckCircle2 size={16}/>ปิดงานแล้ว</span>}</div>
    <div className="stage-progress">{stages.map((stage,index)=><div className={index<=currentIndex?'done':''} key={stage}><span>{index<currentIndex?<CheckCircle2/>:<CircleDot/>}</span><p>{labels[stage]}</p></div>)}</div>
    <div className="detail-grid"><div className="detail-main"><section className="panel detail-card"><div className="panel-header"><div><h2>ข้อมูลลูกค้าและ Brief</h2><p>ข้อมูลที่ส่งต่อระหว่างแต่ละฝ่าย</p></div></div><div className="detail-fields"><div><span>ลูกค้า</span><strong>{job.customer?.name}</strong></div><div><span>เบอร์โทร</span><strong>{job.customer?.phone??'-'}</strong></div><div><span>LINE</span><strong>{job.customer?.line_name??'-'}</strong></div><div><span>กำหนดส่ง</span><strong>{job.deadline?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(job.deadline)):'ไม่ระบุ'}</strong></div><div className="span-2"><span>ความต้องการ</span><p>{job.brief?.requirements}</p></div><div><span>ขนาด</span><strong>{job.brief?.dimensions??'-'}</strong></div><div><span>วัสดุ</span><strong>{job.brief?.material??'-'}</strong></div><div><span>จำนวน</span><strong>{job.brief?.quantity??1}</strong></div></div></section><section className="panel detail-card"><div className="panel-header"><div><h2>Timeline</h2><p>ประวัติสำคัญของ Job</p></div></div><div className="timeline">{activities.map((activity)=><div key={activity.id}><i/><span><strong>{actionLabels[activity.action]??activity.action}</strong><small>{activity.user?.full_name??'ระบบ'} · {new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(activity.created_at))}</small></span></div>)}</div></section></div>
      <aside className="detail-side"><section className="panel finance-card"><div className="panel-header"><div><h2><Banknote size={17}/>การชำระเงิน</h2></div></div><div className="finance-numbers"><span>ยอดทั้งหมด<strong>{money(job.grand_total_satang)}</strong></span><span>ชำระแล้ว<strong className="paid">{money(job.paid_amount_satang)}</strong></span><span>คงเหลือ<strong className={remaining?'unpaid':'paid'}>{money(remaining)}</strong></span></div>{remaining>0?<form action={recordPaymentAction} className="payment-form"><input type="hidden" name="jobId" value={job.id}/><label><span>จำนวนเงิน (บาท)</span><input name="amountBaht" type="number" min="0.01" max={remaining/100} step="0.01" required/></label><label><span>วิธีชำระ</span><select name="method"><option value="PROMPTPAY">PromptPay</option><option value="BANK_TRANSFER">โอนธนาคาร</option><option value="CASH">เงินสด</option><option value="OTHER">อื่น ๆ</option></select></label><label><span>เลขอ้างอิง</span><input name="reference"/></label><button className="primary-button">บันทึกรับชำระ</button></form>:null}<div className="payment-list">{payments.map((payment)=><div key={payment.id}><span><strong>{money(payment.amount_satang)}</strong><small>{payment.method} · {new Intl.DateTimeFormat('th-TH',{dateStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(payment.paid_at))}</small></span><small>{payment.reference}</small></div>)}</div></section><section className="panel info-card"><p><CalendarDays size={15}/>สร้างเมื่อ {new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date(job.created_at))}</p><p><UserRound size={15}/>Admin: {profile.full_name}</p></section></aside>
    </div>
  </AppShell>;
}
